### ISSUE TITLE
Consider using light weight downloader (e.g. `curl`) instead of `reqwest`

### ISSUE THREAD

**Issue by luojia65** [rust-math/intel-mkl-src#17]
Using large web framework is flexible and feature rich, but is somehow expensive in disk space. My matrix calculation program compiles `intel-mkl-src` whick requires a huge web framework by `extern crate reqwest` ([code](https://github.com/rust-math/intel-mkl-src/blob/master/build.rs#L25)), resulting in eaten up almost 3.44GB of disk space only to calculate one dot result of two matrices. If we consider light weight framework e.g. `curl`, we can get rid of large `target` folder space cost and download the source faster (rather than GBs of target + source size).

**Comment by Shnatsel** [comment]
[ureq](https://crates.io/crates/ureq) is a fairly minimal alternative to reqwest. It is synchronous, so it does not pull in the huge tokio dependency.
