### ISSUE TITLE
Do not depend on unnecessary things 

### ISSUE THREAD

**Issue by usamec** [rust-math/intel-mkl-src#28]
This crate depends on `openssl-sys`, which requires system installation of libssl-dev (or something similar). This is completely silly for crate providing math.

**Comment by termoshtt** [comment]
> This is completely silly for crate providing math.

I agree, but we have no option to download the archive of MKL without SSL.

**Comment by usamec** [comment]
Is it possible to use system installed binaries somehow (e.g. curl)?

**Comment by termoshtt** [comment]
We have some options:

(a) Use [curl-rs](https://docs.rs/curl/0.5.0/curl/) (Current)
--------------------------
  - Windows, macOS has default TLS library, so we do not need to install anything
  - Linux does not bundles TSL library, but they can be installed using package manager, e.g. `apt install libssl-dev`

(b) Use `curl` external as program
------------------------------------
  - Recent Windows 10 includes `curl` compatible with Linux one
  - I do not know macOS
  - Linux does not bundles `curl` program, but we can easily install it `apt install curl`

(c) Use reqwest or other lightweight Rust HTTP+TLS crate ( #17 )
--------------------------------------------------------------------
- We needs tokio or other async runtime

---
If we focus on using non-x86 environment, it will be worth trying to omit openssl-sys dependency. However, Intel-MKL itself assumes x86 environment and openssl-sys is easy to use on these platforms.

**Comment by termoshtt** [comment]
related: #29
