### ISSUE TITLE
Consider making downloading MKL opt-in

### ISSUE THREAD

**Issue by Andlon** [rust-math/intel-mkl-src#29]
I'd like to use this crate, as it integrates well with `nalgebra-lapack`, and I like the way the different `src` crates work together.

However, at the moment, it's a bit of a showstopper that the crate downloads an enormous proprietary framework from a random AWS URL, both for security reasons as well as bandwidth considerations, and last but not least stability: what happens if you are no longer able to host the binaries?

Would you be willing to making this behavior opt-in, and instead to use installed MKL libs by default? I'm sorry if this has been discussed before, I could not find any indication of this.

**Comment by termoshtt** [comment]
I will add a `never-download` feature for this.
