### ISSUE TITLE
intel-mkl-tool: Compilation problem with anyhow 1.0.49

### ISSUE THREAD

**Issue by relf** [rust-math/intel-mkl-src#68]
Following the release of anyhow 1.0.49, I get the following compilation error:
<pre>  
...
   Compiling ndarray-linalg v0.14.1
   Compiling zstd v0.5.4+zstd.1.4.7
   Compiling intel-mkl-tool v0.2.0+mkl2020.1
error[E0532]: expected tuple struct or tuple variant, found function `Ok`
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/intel-mkl-tool-0.2.0+mkl2020.1/src/entry.rs:75:16
   |
75 |         if let Ok(dir) = std::env::var("OUT_DIR") {
   |                ^^ not a tuple struct or tuple variant
   |
help: consider importing one of these items instead
   |
1  | use core::result::Result::Ok;
   |
1  | use std::result::Result::Ok;
   |
...
</pre>

It seems like the new `Ok()` function introduced in anyhow breaks the code. see [anyhow 1.0.49 release](https://github.com/dtolnay/anyhow/releases/tag/1.0.49). Pinning anyhow to 1.0.48 solves the problem.
@dtolnay, to also bring this to your attention.

**Comment by YuhanLiin** [comment]
Issue is the `use anyhow::*;` in `lib.rs`, which reexports every item in `anyhow` internally. Since `entry.rs` has the line `use crate::*;`, it also imports every item in `anyhow`, including `Ok`.

**Comment by hombit** [comment]
I've opened #70 to fix it, but we need @termoshtt or another maintainer to merge it

**Comment by JHenneberg** [comment]
same happens for me using 
```toml
ndarray = "0.15"
ndarray-linalg = { version = "0.13", features = ["intel-mkl-system"] }
```

@hombit maybe creating a new fork and continue the developing there if the original author is not handing over this repo or assign new maintainer.

**Comment by hombit** [comment]
@JHenneberg I wrote an email to @termoshtt asking to add new contributors to this repo (all the whole org). Let's wait for a few days

**Comment by JHenneberg** [comment]
> @JHenneberg I wrote an email to @termoshtt asking to add new contributors to this repo (or to the org). Let's wait for a few days

any answer on your site?

**Comment by hombit** [comment]
@JHenneberg no answer
