### ISSUE TITLE
Is this package maintained anymore?

### ISSUE THREAD

**Issue by njaard** [rust-math/intel-mkl-src#69]
If not, can you give me access in some way so that I can do some fixes?

Edit: Forked at https://github.com/njaard/mkl-src/

**Comment by hombit** [comment]
I think you mean `anyhow` issue, I see some activity here: #68

**Comment by JHenneberg** [comment]
Not sure.
@termoshtt , @danieldk , @bytesnake : Is this repository still maintained?
There are few bugs and also PR which I would like to see merged.

**Comment by danieldk** [comment]
> @termoshtt , @danieldk , @bytesnake : Is this repository still maintained?

I don't know? I have only submitted a PR once?

**Comment by JHenneberg** [comment]
@danieldk ok I see.

I am not sure who is the official maintainer because https://github.com/orgs/rust-math/people shows no one. From the accepted PR I was looking threw it is definitely [termoshtt](https://github.com/termoshtt)

**Comment by njaard** [comment]
Can someone with a twitter account try to message @termoshtt ? -> https://twitter.com/termoshtt

**Comment by njaard** [comment]
I have forked this crate: https://github.com/njaard/mkl-src/

With appreciation to @termoshtt I'd like to ask everyone to make further contributions to my fork's repository due to the original author's absence.
